FROM mcr.microsoft.com/dotnet/sdk:5.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["poc/BOTestApi/BOTestApi/BOTestApi.csproj", "poc/BOTestApi/BOTestApi/"]

RUN dotnet restore "poc/BOTestApi/BOTestApi/BOTestApi.csproj"
COPY . .
WORKDIR "/src/poc/BOTestApi/BOTestApi"
RUN dotnet build --no-restore "BOTestApi.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]